apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloneset-demo
spec:
  components:
    - name: csd
      type: clone-set
      properties:
        image: oamdev/hello-world
        volumeMounts:
          configMap:
            - name: config-vol
              cmName: test
              mountPath: /etc/config
        pvcTemplates:
          - name: pvc-test
            mountPath: /mnt123
            storage: 20Gi
      traits:
        - type: scaler
          properties:
            replicas: 2