apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloneset-demo
spec:
  components:
    - name: csd
      type: clone-set
      properties:
        image: oamdev/hello-world
        volumeMounts:
          configMap:
            - name: config-vol
              cmName: test
              mountPath: /etc/config
          pvc:
            - name: test
              mountPath: /mnt
              claimName: test
        volumes:
          - name: test1
            mountPath: /mnt1
            type: emptyDir
      traits:
        - type: scaler
          properties:
            replicas: 2